services:
  vbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: vbot:latest
    container_name: vbot
    restart: unless-stopped
    env_file:
      - .env

    networks:
      - vbot-net

networks:
  vbot-net:
    driver: bridge
